# app/config/services.yml

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# Best Practice: Don't define parameters for the classes of your services and keep your service names short
#service slugger permettant de remplacer dans les slug, les espaces par des -.
    app.slugger:
        class: AppBundle\Utils\Slugger
